"""modify some changes and adjustment to the models

Revision ID: 49ec9d94ea79
Revises: dcdada3348f6
Create Date: 2026-10-04 13:47:49.158614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ec9d94ea79'
down_revision: Union[str, None] = 'dcdada3348f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('photo_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('emoji', sa.String(), nullable=True))
    op.create_foreign_key(None, 'messages', 'photos', ['photo_id'], ['id'])
    op.drop_column('photos', 'reference_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'emoji')
    op.drop_column('messages', 'photo_id')
    # ### end Alembic commands ###
