"""change models user where can create a normal user and claim table to send a proof image

Revision ID: 5acd59a2ab4f
Revises: 49ec9d94ea79
Create Date: 2026-10-05 13:52:15.495454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5acd59a2ab4f'
down_revision: Union[str, None] = '49ec9d94ea79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('image_proof_url', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('claim_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_messages_claim_id'), 'messages', ['claim_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'claims', ['claim_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_claim_id'), table_name='messages')
    op.drop_column('messages', 'claim_id')
    op.drop_column('claims', 'image_proof_url')
    # ### end Alembic commands ###
